id: P006890
initial_creation_type: ocr
source_metadata:
  id: bdr:W3MS109
  title: རོང་པོ་དགོན་ཆེན་དུ་བཞུགས་པའི་དཔེ་རྙིང་དཔེ་དཀོན།
  author: ''
  volumes:
    b8edf80895494b798fad4b2ad21bf419:
      image_group_id: I3MS111
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
